source 'https://github.com/CocoaPods/Specs'

platform :ios, '<%= deployment_target %>'

inhibit_all_warnings!
# Uncomment this line if you use Swift
#use_frameworks!

target '<%= project_name %>' do
	# Application Pods
end

target '<%= test_target_name %>' do 
	inherit! :search_paths
    # Test Pods
end
